version: 2
jobs:
  build:
    ###Name of project
    working_directory: ~/CyclingApp
    docker:
      ###changes SDK version to current version
      - image: circleci/android:api-34
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          ###runs unit tests in test folder
          name: Run InstrumentedTest
          command: ./gradlew test
          ##stores artifacts in this place if build is successful
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apks/
          ##results stored in this path
      - store_test_results:
          path: app/build/test-results
